 name: env_G3DM
 channels:
    - pytorch
    - defaults
    - anaconda
    - conda-forge
    - bioconda
    - dglteam
 dependencies:
    - pytorch
    - torchvision
    - torchaudio
    - cudatoolkit=10.2
    - numpy
    - scipy
    - cooler
    - scikit-learn
    - matplotlib
    - dgl-cuda10.2
    - pip
    - scikit-image
    - pip:
        - gputil
        - tensorboard
        - iced
        - torch_optimizer
      #   - kornia
#        - torchinfo
#        - pykeops
#        - geomloss