 name: env_viz
 channels:
   - defaults
   - anaconda
   - plotly
   - conda-forge
   - bioconda
 dependencies:
   - numpy
   - scipy
   - scikit-learn
   - matplotlib
   - ipympl
   - ipykernel
   - seaborn
   - plotly
   - nbformat
   - pandas
   - nodejs=16
   - ipywidgets
   - pip
   - pip:
      - cooler
      - iced
      - chart_studio