 name: env_viz
 channels:
   - defaults
   - anaconda
   - plotly
   - conda-forge
   - bioconda
 dependencies:
   - numpy
   - scipy
   - scikit-learn
   - matplotlib
   - ipykernel
   - seaborn
   - plotly
   - pip
   - pip:
      - cooler
      - iced