 name: env_viz
 channels:
   - defaults
   - anaconda
   - plotly
   - conda-forge
   - bioconda
   - dglteam
   - pytorch
   - open3d-admin
 dependencies:
   - numpy
   - scipy
   - scikit-learn
   - matplotlib
   - jupyterlab
   - ipykernel
   - seaborn
   - plotly
   - nbformat
   - pandas
   - nodejs=16
   - pytorch
   - torchvision
   - torchaudio
   # - cudatoolkit =10.2
   - dgl #-cuda10.2
   - open3d
   - pip
   - pip:
      - cooler
      - iced
      - chart_studio
      - networkx[default]
      - python-louvain
    
#  - ipywidgets
#  - ipympl